
const MODULE_PREFIX = "HOME_DASHBOARD_MODULE"
const SAGA_PREFIX = MODULE_PREFIX + "__SAGA__"
const REDUCER_PREFIX = MODULE_PREFIX + "__REDUCER__"

export const SAGA_ACTION_TYPES = {
    FETCH_ARTICLES: `${SAGA_PREFIX}_FETCH_ARTICLES`,
    UPDATE_USER_FILTER_SELECTIONS: `${SAGA_PREFIX}_UPDATE_USER_FILTER_SELECTIONS`,
    UPDATE_USER_PREFERENCE: `${SAGA_PREFIX}_UPDATE_USER_PREFERENCE`,
}

export const REDUCER_ACTION_TYPES = {
    SET_PROCESSING: `${REDUCER_PREFIX}_TRANSACTION_PROCESSING`,
    FETCH_ARTICLES_COMPLETED: `${REDUCER_PREFIX}_FETCH_ARTICLES_COMPLETED`,
    UPDATE_USER_FILTER_SELECTIONS_COMPLETED: `${REDUCER_PREFIX}_UPDATE_USER_FILTER_SELECTIONS`,
    UPDATE_USER_PREFERENCES_COMPLETED: `${REDUCER_PREFIX}_UPDATE_USER_PREFERENCES_COMPLETED`,
}